version: "3.8"

services:
  redis:
    image: redis:7.2.4-alpine3.19
    restart: always
    ports:
      - 6379:6379

  asynqmon:
    image: hibiken/asynqmon:0.7.2
    ports:
      - 5040:5040
    environment:
      PORT: "5040"
      REDIS_URL: "redis://@redis:6379/0"
    restart: always
    depends_on:
      - redis
